version: '3.8'

services:
  # database engine service
  postgres_db:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres

  # database admin service
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "9090:8080"

  billingapp-back:
    build:
      context: ./java
      args:
        - JAR_FILE=*.jar
        - DB_PASSWORD=qwerty
    container_name: billingapp-back
    environment:
        - JAVA_OPTS=
          -Xms256M
          -Xms256M
    depends_on:
        - postgres_db
    ports:
        - 8080:8080
  
  billingapp-front:
    build:
      context: ./angular
    container_name: billingapp-front
    depends_on: 
      - billingapp-back
    ports: 
      - 80:80
